themix-project/themix-gui

- change_color.sh
If you try to use a -o argument with spaces in it, things break fantastically. Quoting the paths fixes this. Things will probably also break if oomox's path has spaces, so this fixes that too.
> Fix paths with potential spaces in change_colors.sh

- gui/helpers.py
Previously, `save_colorscheme` would write colorscheme keys in a random order, so that each new instance of oomox will save the same colorscheme values in different orders. If a user would like to keep their schemes version-controlled, this makes diffs messy.
Instead, when saving colorscheme keys, we write them in sorted order so that they can be sensibly version-controlled.
> Improve save_colorscheme to be deterministic

- scripts/mix.sh
Some locales use a different fractional separator than `.`, like French which uses `,` (e.g. `123,4`). This confuses `printf` which doesn't understand `bc`'s output and leads to it falling back on `0` as the value.
Fix this by performing the truncation directly in `bc` itself.
---
Alternatively you could set `LC_NUMERIC=C` in the `printf` sub-shell, but it seems best to truncate in `bc` as it's possible.
> fix(scripts/mix.sh): fix floating-point truncation on non-C locales

- change_color.sh
- gui/preview.py
- gui/theme_model.py
- src/gtk-2.0/gtkrc
- src/gtk-3.0/scss/_global.scss
- src/gtk-3.0/scss/widgets/_base.scss
- src/gtk-3.20/scss/_global.scss
- src/gtk-3.20/scss/widgets/_base.scss
- src/gtk-3.20/scss/widgets/_entry.scss
- src/gtk-3.20/scss/widgets/_view.scss
Changing the caret size and colors is especially useful for accessibility purposes, e.g. for people with low vision having a larger and more outstanding caret is best.
> feat(change_colors, gui): add support for theming the caret

- gui/helpers.py
I introduced it in 40260ae386a19bf7a1adf0bcb0af9c027eb976f6, sorry
Kind of weird Python 3.5 liked it.  Doesn't affect much otherwise as currently no keyword arguments are used.
> fix(gui): fix typo breaking Python 3.4 support

- gui/main.py
Gio.PropertyAction.new() has a bug on older python3-gi, at least up to
3.14, which leads to https://bugzilla.gnome.org/show_bug.cgi?id=683599.
> fix(gui): support older python3-gi

- gui/export.py
Guard a newer function call and simplify some code for supporting running on GTK 3.14.
The themes work almost flawlessly there too, only the `:not` pseudo-class used for scrollbar overlay-indicator seem not to be recognized; but I'm not even sure overlay indicators are a thing on 3.14.
> feat(gui): GTK 3.14 support

- .gitignore
- PKGBUILD
- gui/colors_list.py
- gui/export.py
- gui/main.py
- gui/presets_list.py
- gui/preview.py
- gui/theme_model.py
- po.mk
- po/fr.po
Add i18n support (using gettext module) and an initial French translation.
`po.mk` might need to be enhanced, because although now it's nicely automatic, it might be annoying to update the `.po` automatically when the Python sources changes (well, when running `po.mk install`, which is the default), as the `.po` are checked in source yet partially generated and containing source references, and thus can lead to extra diff.  Not 100% sure what the best thing would be here… probably the same but not automatically rebuilding the `.po` when sources changes, but only with the `update-po` target.
Also, it could also be interesting to translate scripts at some point, which is totally doable using gettext, and should be straightforward to add to this infrastructure.
> GUI: Add internationalization support

- README.md
I just created a repository on [Fedora Copr](https://copr.fedorainfracloud.org/) and put an [oomox package](https://copr.fedorainfracloud.org/coprs/tcg/themes/packages/) on it. It's available for Fedora 24 and 25 users in just two commands, so I thought mentioning it in the README could be helpful for other Fedora users.
> doc(readme): add Fedora Copr instructions

- oomox_gui/colors_list.py
Entering more characters breaks some part of the code, so try and prevent the user from doing so.
> Prevent entering more than 6 letters in color entry fields

- scripts/mix.sh
What was wrong with it? We were multiplying hex integers with decimal fractions, effectively almost halving any ratio passed to it. So instead of calculating in hex, we convert to decimal first.
I'm going to try again to do my optional color stuff, but I noticed this was broken so I wanted to fix it first.
> Fix mix.sh.

- archdroid.sh
- change_color.sh
- colors/xresources
- gnome_colors.sh
- oomoxify.sh
- scripts/darker.sh
- scripts/hex_to_rgba.sh
- scripts/is_dark.sh
- scripts/mix.sh
- scripts/render-assets.sh
- scripts/utils.sh
- src/assets/change_dpi.sh
This PR makes things compatible with non-Linux systems, more specifically FreeBSD (but I expect other BSDs and/or Solaris to require these changes, as well).
The changes:
* don't expect bash to bin in /bin, look for it with env
* `readlink -e` is not universally supported, but `readlink -f` is
*  `sed -i` needs a backup suffix for non-gnu sed.
* the default behaviour for `cp -r FOO/` is to copy the contents of FOO, not the FOO directory so I removed trailing / in the PATHLIST
I haven't checked the effect of the changes on Linux, but I am *rather* sure they should have no effect
> [FIX] make compatible with non-Linux (tested on FreeBSD)

- packaging/install.sh
When downloading a tar.gz/zip archive of oomox from Github, files begining with a dot (`.editorconfig`, `.flake8`...) are automatically removed from the archive, and executing `./packaging/install.sh` fails because it can't remove them.
> Force rm in case files don't exist

- README.md
pacaur is no longer maintained (https://github.com/rmarquis/pacaur) 
trizen is a good replacement because it has the same syntax as pacaur.
> switch from pacaur to trizen

- packaging/ubuntu/control
Fixes #133 
On Ubuntu xenial based systems it was possible to install Oomox Deb with an incompatible version of libsass0 from the xenial repos which would result in Oomox GUI failing to build themes.
This commit enforces minimum versions for both sassc and libsass0
Ubuntu xenial users can source compatible versions of both packages via https://packages.ubuntu.com/bionic/sassc and https://packages.ubuntu.com/bionic/libsass0
> Ubuntu Deb - specify minimum sassc (>=3.4) and libsass0 (>=3.4)

- plugins/theme_arc/oomox_plugin.py
- plugins/theme_oomox/oomox_plugin.py
All theme colors should be in Colors section for less user confusion.
> Move all theme colors to colors section

- po/es.po
- po/fr.po
- po/it.po
- po/nl_NL.po
- po/pt_BR.po
- po/pt_PT.po
Hello @actionless !
I updated the Dutch, Italian, Portuguese and Spanish translations.
I am still upgrading French translation.
You missed few strings not included in the PO files:
1. Colors from Image:
2. "Text caret" and "BiDi textbox caret":
3. "Selected Background" (it also is misspelled) and "Selected Text":
4. "Enable Theme Transparency":
> Updated translations

- po/es.po
- po/fr.po
- po/it.po
- po/nl_NL.po
- po/pt_BR.po
- po/pt_PT.po
Hello @actionless !
* I have fixed the misspeling "Backround" to "Background" in all Dutch, French, Italian, Portuguese and Spanish;
* I have removed the duplicated strings `#~ msgid "Theme options:"` in all Dutch, French, Italian, Portuguese and Spanish;
* I have removed "fuzzy" and fixed missed symbols in the Dutch translation;
* I have corrected the misspellings, fuzzy translations and improved the other translations in the French, Italian, Portuguese and Spanish.
BiDi is the same in all languages. But I do not know if it is bad to insert the whole name of that abbreviation like: "testo bidirezionale", "texto bidireccional", "texte bidirectionnel", "bidirectionele tekst", etc.
> [Fixed conflicts] Fixed misspellings and fuzzy translations in Dutch, French, Italian, Portuguese and Spanish

- colors/Xresources/xresources-reverse
- scripted_colors/xresources/xresources-reverse
A few months ago I whipped up the `xresources-reverse` theme to create a pywal themed "dark mode" theme. However the when a menu item is selected, the text is extremely hard to read against the bright selection highlight.
Now text shown for a selected item is black, or the color of the background so the contrast is better!
> fixed highlighted text color

- packaging/ubuntu/Dockerfile_cosmic
- packaging/ubuntu/Dockerfile_zesty
- packaging/ubuntu/create_ubuntu_package.sh
- packaging/ubuntu/prerm
Using fakeroot creates a package with the right ownership.
Cleaning precompiled .pyc files generated from postinst avoids leaving files behind us when uninstalling and prevents the corresponding dpkg warning to show up.
> Enhance ubuntu packaging with fakeroot usage and __pycache__ cleanup

- oomox_gui/colors_list.py
I probably need help on this; but I _really_ want to be able to change all matching colors in the ColorsList globally somehow. With this pull, you can functionally right click on a colorbutton and all rows with matching colors will also be changed to the selected color.
It's a small modification, but it's definitely not done the correct way. Please point me in the correct direction.
Modified colors_list.OomoxColorButton:
* changed __init__ so that on_click is linked to "button_pressed_event" event vs. "clicked" signal to allow to detect left(1) vs right(3) click
* implemented get_listbox_parent to reference button's parent ListBox object
* changed colors_list.OomoxColorButton.on_click to use the above to iterate through sibling listboxrows and modify those that match the original value
* …
> Added hacky drop-down with "replace all instances" on color rows

- oomox_gui/main.py
This commit swap `FileChooserDialog` for `FileChooserNative`. This enables
supports for Flatpak portals, which allows applications within Flatpak
sandbox to access files outside of the sandbox on user's request.
See https://docs.flatpak.org/en/latest/portals-gtk.html for more
details.
> oomox_gui: add support for file chooser portals

- packaging/arch/PKGBUILD_gui
> Add missing python-cairo dependency on Arch

- oomox_gui/terminal.py
This resolves an xgettext error when building.
> Add utf-8 hint to to oomox_gui/terminal.py

- packaging/arch/PKGBUILD_icons_archdroid
- packaging/arch/PKGBUILD_icons_gnome_colors
- packaging/arch/PKGBUILD_icons_numix
- packaging/arch/PKGBUILD_icons_papirus
- packaging/arch/PKGBUILD_icons_suruplus
- packaging/arch/PKGBUILD_icons_suruplus_aspromauros
- packaging/arch/PKGBUILD_theme_arc
- packaging/arch/PKGBUILD_theme_materia
On my machine, the build fails with `shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory` at the `python -O -m compileall [...]` line. The line immediately before the issue manifests deletes the cwd (`rm -fr "$pkg_tmp_dir"`). makepkg succeeds when either `rm -fr "$pkg_tmp_dir"` is removed or `cd -` is added right before it.
I'm having difficulty determining why this happens in my environment. It happens for me in both bash and zsh (and `bash --norc --noprofile`). The issue has existed for months, so it's likely not some other package being broken. Probably some configuration values for python or the shells are causing it.
This is the only PKGBUILD I've had this issue with, and deleting the cwd seems iffy enough to be worth …
> PKGBUILD quick fix for certain environments

- plugins/icons_papirus/change_color.sh
the papirus icons theme removed the custom folders due to a change in folder colors to stop supporting custom colors, instead we use the red folders as template to build the custom colored folders.
with this there won't be any loss of functionality after updating the papirus icons submodule.
> change: use red folders as base for custom color
